DROP DATABASE IF EXISTS tvDB;
CREATE database tvDB;

USE tvDB;

CREATE TABLE tvshow (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NULL,
  genre VARCHAR(100) NULL,
  network VARCHAR(100) NULL
);

CREATE TABLE tvcharacter (
  characterid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NULL,
  quote VARCHAR(1000) NULL,
  show_id INT NULL,
  CONSTRAINT `FK_show` 
  FOREIGN KEY (show_id)
  REFERENCES tvshow(id)
  ON DELETE CASCADE
  );

